### ISSUE TITLE
Week 4 Ready 

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#2]
@pawaitemadisoncollege week 4 is ready.  I decided to use my indie project for the exercise.  

We did a lot of CRUD in advanced PHP so I feel pretty comfortable with this.  We also did a little in .NET.  We utilized the entity framework in C# so this week was almost like a review but with a twist. The thing that seemed foreign was how java works with hibernate and mostly syntax.  But that is something that will just get better with practice.  

The challenging thing this week was testing.  I wanted to have meaningful tests.  I did have my husband hash this out with me.  I initially was hardcoding what I expected out of the code, but then as your DB gets fiddled with, the tests fail because the id is no longer what it was.  To avoid all of that, I needed to think more about how to test a dynamic DB and how to get those expected values when I didn't know what they would be.  I also created some before and after test code to help manage all of the moving pieces and also to refactor and pull out the repeated code (creating a new test user each time). These tests did actually shed light on some real bugs and missing lines in my DAO.  The tests doing their magic! 

I'm hoping to have more time this week to make some progress on the indie project and get ahead.  This last week was just way too busy!

**Comment by pawaitemadisoncollege** [comment]
I'm glad to see that you took the time to implement hibernate right away in your indie project and that you are seeing parallels to php and .net's entity framework!

Yes! @llandritsch. Testing the db poses an interesting challenge, right? I tend use this approach: execute a setup task that creates a fresh test db before each run (that's the cleandb.sql from the demos), so that all the data I need is there and consistent each time. This is particularly useful as we start adding more tables and the relationships become more complex. AND, this way I don't have to rely on my DAO working correctly to populate by db either!

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually.
