### ISSUE TITLE
Week 5 Ready

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#3]
@pawaitemadisoncollege Week 5 is ready for review.  I did the exercise in my indie Project again. 

This week started off swimmingly as it felt like just reviewing from last week but with a few extra annotations.  However, it changed quickly when I realized that I needed to have some extra annotations because my DB was named less generically. That definitely taught me a lesson about future creation and not just accepting what a tool spits out.  However, I feel like I might understand hibernate a little bit better because I needed to sift through some of the docs provided and traversed the expanse of google! I also had trouble getting my cleandb to work this week.  intellij was complaining that it couldn't find the mySql driver, but it was clearly executing all other statements because it was CRUDing everything it was supposed to.  It just didn't like the sql file. Instead of fighting with it any longer, I decided to just create deleteAll methods in my DAO's and call those in my BeforeEach.  Overall, a good week!

**Comment by pawaitemadisoncollege** [comment]
Great progress with this in your indie project @llandritsch!

- [ ] Let's work through that driver not found issue. I don't see anything odd in the database.properties file, so I think I'd start by setting a breakpoint here: https://github.com/llandritsch/Meal-and-grocery-list-builder/blob/887ac33e6733b3ffe9df33a748ed25c8f64e0b08/src/test/java/test/util/Database.java#L63, to see if the properties are properly loaded, specifically the driver property, and then continue stepping along to see the full error stack trace. 
- [ ] I think I had a typo in one my examples that likely led you right into this: 
<img width="1782" alt="Screen Shot 2021-02-22 at 3 46 09 PM" src="https://user-images.githubusercontent.com/13874466/108774469-537ef100-7525-11eb-9b19-f615a82f08db.png">. The fix should be to search for any `${filepath}` references and instead use filename which is defined here: https://github.com/llandritsch/Meal-and-grocery-list-builder/blob/887ac33e6733b3ffe9df33a748ed25c8f64e0b08/src/main/resources/log4j2.properties#L2
- [ ] I'd recommend sticking with a single log4j2.properties file. I don't *think* there's a strong reason to use a test version?
- [ ] Think about testing the delete scenarios in one-to-many relationships more fully. For example, if a user is deleted, what should happen to their recipes? What if a recipe is deleted? Write tests to make sure whatever _should_ happen, _does_ happen.
- [ ] You'll likely notice, if you haven't already, that writing a Dao for each entity will be very repetitive - watch for the abstract/generic dao to be introduced in the coming week and plan to use it in your project so that you can use a single dao! Note that you will still have unit tests each for each entity(dao) to make sure that annotations and database relationships are set up correctly.
- [ ] I recommend using a cleandb.sql file or similar to create your test users so that you are not dependent on the very classes that you are trying to test. https://github.com/llandritsch/Meal-and-grocery-list-builder/blob/887ac33e6733b3ffe9df33a748ed25c8f64e0b08/src/test/java/persistence/RecipesDAOTest.java#L39-L55
- [ ] There's an important test commented out here: https://github.com/llandritsch/Meal-and-grocery-list-builder/blob/887ac33e6733b3ffe9df33a748ed25c8f64e0b08/src/test/java/persistence/UsersDAOTest.java#L83-L99.
