### ISSUE TITLE
checkpoint 2 ready

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#7]
@pawaitemadisoncollege checkpoint 2 ready!  Sorry things are last minute this last week!  It's been a week of stress and lots of family stuff going on! I hope to be much more organized going forward!

**Comment by pawaitemadisoncollege** [comment]
You've done a nice job implementing the weekly tech into your project and it really shows in CP2. 

A few things:
- [ ] Log statements when an exception is caught should probably be log.error level instead of info.   Also printstacktrace will go directly to the tomcat logs, so those should also be written to the logs: log.error("Your description here", exception);
![Screen Shot 2021-03-08 at 4 29 22 PM](https://user-images.githubusercontent.com/13874466/110390520-bc895d00-802b-11eb-9ad0-2cf178561e9b.png)
- [ ] Much of this work is iterative, so it's likely this is coming yet. Curious where the fact that an item should be added to the grocery list will be stored. Also the category (produce, meat, bakery - mmmm, etc) for an item on the grocery list?
- [ ] Reminder to add in the generic dao (see fat bike trail reports for a good starting point on this class) and remove the entity-specific daos.
